pipeline:
  identifier: Build_scott_cs_webgoat_1716250581070
  name: Webgoat-build
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1716250548234
        repoName: scott-cs/webgoat
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8.3-openjdk-17
                    shell: Sh
                    command: mvn clean package dependency:copy-dependencies
              - step:
                  type: Run
                  name: check dependencies
                  identifier: check_dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: mvn dependency-check:check -U -DskipTests
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/target/*.xml
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
